### ISSUE TITLE
Make sure LEDs and (Wash Lights + 2 Spot Lights) send on unique DMX outputs

### ISSUE THREAD

**Issue by JoshuaBatty** [MindBuffer/cohen_gig#12]
Currently, it looks like the wash_colors and led_colors are being packed into the same dmx buffer. We will need to be able to send 2 unique lines of dmx, one to the LED's and one to the house lighting console which will control the house wash lights and 2 spot lights.

**Comment by mitchmindtree** [comment]
**Second Output**

This should be pretty easy - we'll probably want two textboxes so we can specify their static IPs like we have one for OSC (currently we just broadcast the DMX everywhere, but that won't work if we have two outputs lol).

**Ordering**

Hmm maybe a list where you can see all the washes numbered 0-27 in order of their layout, and then a number dialer next to each that lets you specify their starting DMX channel index? Then the wash colours can be written to the buffer based on these indices? I think this might be the easiest to throw together in a small amount of time?

**Comment by JoshuaBatty** [comment]
Yep i'm happy with both of those suggestions. 

Would also be good to include a way to set the start address for the 2 spot lights as well. They have either 1 or 3 channels of data depending on how they have been configured on the device.

**Comment by mitchmindtree** [comment]
Hmmmm after looking at the source, it doesn't look like the `sacn` crate allows us to specify the exact target IP. When using the `DmxSource::with_ip` constructor, the IP specified simply changes what IP address the UDP socket *binds* to (`0.0.0.0` by default) and not what it *sends* to.

Instead, the exact target IP addr seems to be derived half from some static broadcast channel and half from the universe. E.g. at [this line](https://docs.rs/sacn/0.4.4/src/sacn/source.rs.html#104) we can see the IP address to which data is sent is retrieved. Here's what the function looks like that creates that IP:
```rust
fn universe_to_ip(universe: u16) -> Result<String> {
    if universe == 0 || universe > 63999 {
        return Err(Error::new(
            ErrorKind::InvalidInput,
            "universe is limited to the range 1 to 63999",
        ));
    }
    let high_byte = (universe >> 8) & 0xff;
    let low_byte = universe & 0xff;
    Ok(format!("239.255.{}.{}:5568", high_byte, low_byte))
}
```

It looks like only the last two bytes of the target IP ever change, and they are determined as the high and low bytes of the universe value. I suspect this is probably just part of the sACN specification? Will do some reading.

@JoshuaBatty we might have to have a chat on how to best handle this. Seeing as you can only be on a single network at a time, and you will be connected to both of these separate DMX devices via the network, maybe the correct approach is to see if Jobe can offset the starting universe of the LEDs so that it does not conflict with that of the wash lights? That way we still interface with both of the DMX devices via one `sacn::DmxSource` and differentiate between them with a universe offset instead?

Either way, as a result of all this, it doesn't really make sense for me to add DMX source IP text boxes. If we can confirm that Jobe can offset the starting universe for the LED strips than I can add a little number dialer that allows us to specify the LED strip starting universe :+1:

**Comment by mitchmindtree** [comment]
- [ ] Add a number dialer for the wash and spot universe.
- [ ] Add a number dialer for the universe that the LED strips should start from.
